# Default image and tag
image:
  repository: 10.70.0.28:4321/banjar-unhan/bahan-ajar-cms
  tag: "latest"
  pullPolicy: IfNotPresent

# Replica settings
replicaCount: 1

# Resources
resources:
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    cpu: 400m
    memory: 600Mi

# Common labels you might override
labels:
  service: "bahan-ajar-cms"
  partOf: "banjar-unhan"
  environment: "staging"
  team: "backend"
  version: "v1.0.0"

# Common annotations (e.g. for auto-reload or other operators)
annotations:
  reloader.stakater.com/auto: "true"

# Exposed container port
containerPort: 1339

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 1339

# Ingress configuration
ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: bahan.ajar.cms.10.70.0.45.nip.io
      path: /
  tls: []
