replicaCount: 1

image:
  repository: "10.70.0.28:4321/banjar-unhan/bahan-ajar-cms"
  tag: "latest"
  pullPolicy: "Always"

deployment:
  annotations:
    reloader.stakater.com/auto: "true"

# Example labeling values (each has a fallback in _helpers.tpl)
labels:
  app.kubernetes.io/name: "backend-service"
  app.kubernetes.io/instance: "backend-v1"
  app.kubernetes.io/component: "api"
  app.kubernetes.io/part-of: "ecommerce-platform"
  app.kubernetes.io/managed-by: "helm"
  environment: "staging"
  team: "payments"
  version: "v1.2.3"

resources:
  requests:
    cpu: "200m"
    memory: "300Mi"
  limits:
    cpu: "400m"
    memory: "600Mi"

# Port can also be parameterized if desired:
containerPort: 1339
