# Default values for backend-app

# Common metadata
nameOverride: ""
fullnameOverride: ""

labels:
  # Extra labels you want to attach to resources
  # You can add any standard or custom labels here
  # e.g. "monitoring": "loki"
  monitoring: "loki"

# Annotations for deployment
annotations:
  reloader.stakater.com/auto: "true"

# Deployment configuration
replicaCount: 1

image:
  repository: "10.70.0.28:4321/banjar-unhan/bahan-ajar-cms"
  tag: "latest"
  pullPolicy: "Always"

# Pod/Container settings
podLabels: {}
podAnnotations: {}

# Ports
service:
  port: 1339

# Resources
resources:
  requests:
    cpu: "200m"
    memory: "300Mi"
  limits:
    cpu: "400m"
    memory: "600Mi"

# Environment variables
envFrom:
  configMapRef: "bahan-ajar-config"

# Kubernetes namespace (can also be set during installation via --namespace)
namespaceOverride: "banjar-unhan"
