# Default labels and their values
labels:
  component: api
  partOf: ecommerce-platform
  environment: staging
  team: payments
  version: v1.2.3
  # "managed-by" is set to "helm" by default in the templates/_helpers.tpl

image:
  repository: 10.70.0.28:4321/banjar-unhan/bahan-ajar-cms
  tag: latest
  pullPolicy: Always
  imagePullSecrets:
    - name: regcred

deployment:
  enabled: true
  replicas: 1

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 1339

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: bahan.ajar.cms.10.70.0.45.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - example.com

resources:
  limits:
    cpu: 400m
    memory: 600Mi
  requests:
    cpu: 200m
    memory: 300Mi

# Example: environment variables from config map or secrets
envFrom:
  - configMapRef:
      name: bahan-ajar-config

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
